### ISSUE TITLE
using Exec() for Insert

### ISSUE THREAD

**Issue by cryptix** [Isted/StreetCRUD#2]
Hi,

I think you also want to use `Exec()` to insert data, [not `QueryRow()`](https://github.com/Isted/StreetCRUD/blob/master/examples/UsesGeneratedCode/models/user.go#L96). You already do this for `UPDATE` and `DELETE`s.

ps: [go-database-sql.org](http://go-database-sql.org/modifying.html) has some great insight into this, you might also want to investigate the usage of transactions?

**Comment by Isted** [comment]
Hi Henry,

Thanks for the feedback. I also wanted to use Exec() initially, but you have to use QueryRow to get back the newly inserted key because the pq driver doesn't support LastInsertId (maybe because Postgres uses Sequences). You have to use the Postgres RETURNING statement, and then Scan for what you expect to be returned. Apparently it's because the result you can get back from Postgres can be more complicated than an integer, such as an UUID. Thanks again and I'll take a look at your other issue later today to see if error handling can be improved for InitDataLayer().

Also, I'd definetly like to add support for transactions down the road.

**Comment by cryptix** [comment]
Right!

I totally forgot that I was bitten by this once, too. I found the [sequence functions](http://www.postgresql.org/docs/9.4/static/functions-sequence.html) quite useful in this case:
```go
		qry := `INSERT INTO users (username, hashedpassword) VALUES($1, $2)`
		_, err := s.tx.Exec(qry, a.User, a.HashedPW)
		if err != nil {
			return err
		}

		var id int64
		err = s.tx.QueryRow(`select lastval()`).Scan(&id)
		if err != nil {
			return err
		}
```
.. but  I was also using transactions so this maybe should be deferred until you have them as well.

And some tests on other datatypes maybe but I think this shouldn't be a problem if postgres can build a sequence on them and the `sql.Scanner` interface is implemented properly.
